name: 0.0.$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - group: ado-vmss-pool
  - name: DEBIAN_FRONTEND
    value: noninteractive
  - name: TF_IN_AUTOMATION
    value: true

stages:
  - stage: 'bootstrap'
    pool: 'ado-vmss-pool-bootstrap'
    jobs:
      - job: 
        displayName: 'Generate Agent Image'
        timeoutInMinutes: 600
        cancelTimeoutInMinutes: 30
        steps:
          - checkout: self
            fetchDepth: 1

          - task: Bash@3
            displayName: 'Install Tools'
            inputs:
              targetType: 'inline'
              script: |
                set -euo pipefail
                
                INSTALLER_FOLDER="./agents/bootstrap/scripts/installers"
                chmod -Rv 777 "${INSTALLER_FOLDER}/"
                
                declare -a SCRIPTS=(
                                    "azure-cli.sh"
                                    "basic.sh"
                                    "packer.sh"
                                    "terraform.sh"
                                    )
                
                for SCRIPT in "${SCRIPTS[@]}"
                do
                  sudo -E sh -c "${INSTALLER_FOLDER}/${SCRIPT}"
                done  